// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/grpc/proto/championship_season.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChampionshipSeason struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Championship *Championship `protobuf:"bytes,1,opt,name=championship,proto3" json:"championship,omitempty"`
	Season       *Season       `protobuf:"bytes,2,opt,name=season,proto3" json:"season,omitempty"`
}

func (x *ChampionshipSeason) Reset() {
	*x = ChampionshipSeason{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_championship_season_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChampionshipSeason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChampionshipSeason) ProtoMessage() {}

func (x *ChampionshipSeason) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_championship_season_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChampionshipSeason.ProtoReflect.Descriptor instead.
func (*ChampionshipSeason) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_championship_season_proto_rawDescGZIP(), []int{0}
}

func (x *ChampionshipSeason) GetChampionship() *Championship {
	if x != nil {
		return x.Championship
	}
	return nil
}

func (x *ChampionshipSeason) GetSeason() *Season {
	if x != nil {
		return x.Season
	}
	return nil
}

var File_api_grpc_proto_championship_season_proto protoreflect.FileDescriptor

var file_api_grpc_proto_championship_season_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x74, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6d, 0x70,
	0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6d, 0x70, 0x69, 0x6f, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x6d, 0x70, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x12, 0x25, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x76, 0x61, 0x6e, 0x2d, 0x73, 0x61, 0x62, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_grpc_proto_championship_season_proto_rawDescOnce sync.Once
	file_api_grpc_proto_championship_season_proto_rawDescData = file_api_grpc_proto_championship_season_proto_rawDesc
)

func file_api_grpc_proto_championship_season_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_championship_season_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_championship_season_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_proto_championship_season_proto_rawDescData)
	})
	return file_api_grpc_proto_championship_season_proto_rawDescData
}

var file_api_grpc_proto_championship_season_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_grpc_proto_championship_season_proto_goTypes = []interface{}{
	(*ChampionshipSeason)(nil), // 0: proto.ChampionshipSeason
	(*Championship)(nil),       // 1: proto.Championship
	(*Season)(nil),             // 2: proto.Season
}
var file_api_grpc_proto_championship_season_proto_depIdxs = []int32{
	1, // 0: proto.ChampionshipSeason.championship:type_name -> proto.Championship
	2, // 1: proto.ChampionshipSeason.season:type_name -> proto.Season
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_championship_season_proto_init() }
func file_api_grpc_proto_championship_season_proto_init() {
	if File_api_grpc_proto_championship_season_proto != nil {
		return
	}
	file_api_grpc_proto_championship_proto_init()
	file_api_grpc_proto_season_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_proto_championship_season_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChampionshipSeason); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_proto_championship_season_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_grpc_proto_championship_season_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_championship_season_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_championship_season_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_championship_season_proto = out.File
	file_api_grpc_proto_championship_season_proto_rawDesc = nil
	file_api_grpc_proto_championship_season_proto_goTypes = nil
	file_api_grpc_proto_championship_season_proto_depIdxs = nil
}
