// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/grpc/proto/season.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Season struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	StartYear uint32 `protobuf:"varint,2,opt,name=startYear,proto3" json:"startYear,omitempty"`
	EndYear   uint32 `protobuf:"varint,3,opt,name=endYear,proto3" json:"endYear,omitempty"`
}

func (x *Season) Reset() {
	*x = Season{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_season_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Season) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Season) ProtoMessage() {}

func (x *Season) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_season_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Season.ProtoReflect.Descriptor instead.
func (*Season) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_season_proto_rawDescGZIP(), []int{0}
}

func (x *Season) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Season) GetStartYear() uint32 {
	if x != nil {
		return x.StartYear
	}
	return 0
}

func (x *Season) GetEndYear() uint32 {
	if x != nil {
		return x.EndYear
	}
	return 0
}

var File_api_grpc_proto_season_proto protoreflect.FileDescriptor

var file_api_grpc_proto_season_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x59, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x59, 0x65, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x64, 0x59, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x59, 0x65, 0x61, 0x72, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x76, 0x61, 0x6e, 0x2d, 0x73, 0x61, 0x62, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_proto_season_proto_rawDescOnce sync.Once
	file_api_grpc_proto_season_proto_rawDescData = file_api_grpc_proto_season_proto_rawDesc
)

func file_api_grpc_proto_season_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_season_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_season_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_proto_season_proto_rawDescData)
	})
	return file_api_grpc_proto_season_proto_rawDescData
}

var file_api_grpc_proto_season_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_grpc_proto_season_proto_goTypes = []interface{}{
	(*Season)(nil), // 0: proto.Season
}
var file_api_grpc_proto_season_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_season_proto_init() }
func file_api_grpc_proto_season_proto_init() {
	if File_api_grpc_proto_season_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_proto_season_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Season); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_proto_season_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_grpc_proto_season_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_season_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_season_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_season_proto = out.File
	file_api_grpc_proto_season_proto_rawDesc = nil
	file_api_grpc_proto_season_proto_goTypes = nil
	file_api_grpc_proto_season_proto_depIdxs = nil
}
